### ISSUE TITLE
Competition / Misc Issues

### ISSUE THREAD

**Issue by serpient** [luoto/chingu-frontend#145]
- [x] project sidebar external links styling
- [x] check projectShowcase error button styling after #205 #206 #199 merge
- [x] Remove `skills` from teamQuery and newsfeedQuery  #210
- [x] ` info.data is undefined` on TeamCard in dev #210
- [x] `Store error: the application attempted to write an object with no provided id but the store already contains an id of...` on new mutations - Check again after sprint/showcase merge
- [x] some buttons show type cursor oh hover
